- spellcasting
  - druid spell_known/5 logic veralgemenen
  - gekende spells filteren uit learn_spell lijstjes
  - oorsprong van spells tonen
  - warlock eldritch invocation spells ondersteunen
  - spell effects terug introduceren
  - simpele DC based spells zoals sacred flame toevoegen aan attack table
  - archdruid correct implementeren

- alternatief voor trait_options: een waarbij je niet rechtstreeks je traits kiest maar opties die expanded worden naar traits, om af te raken van "trait pollution", zoals het learn_spell trait

- leesbare error messages
- effecten van short en long rests registreren
- "asserted"/GM fiat traits toevoegen
- manuele overrides toevoegen
- beast json
- lege tabellen (bv spell prep) niet tonen
- ergens een lijst van talen toevoegen; of meer algemeen: omgaan met het idee "kies van deze lijst, of vul gewoon zelf iets in"

- onderscheid tussen initial class exclusive traits en reguliere level 1 traits (zie https://5thsrd.org/rules/multiclassing/#proficiencies)

  
* huidige todo
Bezig met warlock class.
Deze class heeft identieke functionaliteit nodig als sorcerers voor het leren van spells.
Dit moet dus veralgemeend worden.
Ik wil een algemeen idee van "novel spells" -> learnable spells die niet al gekend zijn.
Ik wil ook een algemeen systeem voor het vergeten en vervangen van spells.
